### ISSUE TITLE
Need to fix `transaction/create`

### ISSUE THREAD

**Issue by Courtcircuits** [Courtcircuits/ratathune-server#1]
There is a problem, need to investigate : 
```json
{
    "message": "select * from \"room_user\" where \"user_id\" = $1 and \"room_id\" = $2 - relation \"room_user\" does not exist",
    "stack": "error: select * from \"room_user\" where \"user_id\" = $1 and \"room_id\" = $2 - relation \"room_user\" does not exist\n    at Parser.parseErrorMessage (/home/mihai/Projets/Ratathune/server/ratathune/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/home/mihai/Projets/Ratathune/server/ratathune/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/home/mihai/Projets/Ratathune/server/ratathune/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/home/mihai/Projets/Ratathune/server/ratathune/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
    "code": "42P01"
}
```

**Comment by Courtcircuits** [comment]
Ok c'est bon : 
![image](https://github.com/Courtcircuits/ratathune-server/assets/90451752/ead7863d-0e22-4a5b-9d0f-04d095f3b1db)
